### ISSUE TITLE
`mkcert -csr` fails if the CSR has no SANs

### ISSUE THREAD

**Issue by rajiv** [FiloSottile/mkcert#372]
The `-csr` option for mkcert requires a CSR that contains a SAN list (X509v3 Subject Alternative Name extension). Without that extension (and hostnames in the list), mkcert panics:

```
$ mkcert -version
v1.4.3
$ mkcert -csr cn-only.example.com.csr 
Note: the local CA is not installed in the system trust store.
Note: the local CA is not installed in the Firefox trust store.
Run "mkcert -install" for certificates to be trusted automatically ⚠️
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.(*mkcert).fileNames(0xc0000bff00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x121fc40, 0xc0000aa120, 0xc000468000, 0x486)
	/private/tmp/mkcert-20201126-31141-a1fv3f/mkcert-1.4.3/src/github.com/FiloSottile/mkcert/cert.go:177 +0x3cc
main.(*mkcert).makeCertFromCSR(0xc0000bff00)
	/private/tmp/mkcert-20201126-31141-a1fv3f/mkcert-1.4.3/src/github.com/FiloSottile/mkcert/cert.go:266 +0x7c8
main.(*mkcert).Run(0xc0000bff00, 0xc00011e1a0, 0x0, 0x0)
	/private/tmp/mkcert-20201126-31141-a1fv3f/mkcert-1.4.3/src/github.com/FiloSottile/mkcert/main.go:203 +0x64a
main.main()
	/private/tmp/mkcert-20201126-31141-a1fv3f/mkcert-1.4.3/src/github.com/FiloSottile/mkcert/main.go:145 +0x851
```

mkcert could be more friendly to the user and automatically include the CN from the Subject field (if it exists) as one of the hosts in the list.

**Comment by rajiv** [comment]
Duplicate of #318. PR in #344.
