### ISSUE TITLE
Not working with python requests.

### ISSUE THREAD

**Issue by shomanishikawa** [FiloSottile/mkcert#49]
Currently have a local app running on localhost. (running OSX)

Created certificates with 

```
mkcert -install
mkcert localhost
```
and also did `brew install nss` and reran install to fix firefox.

On node, this works fine like so, and I'm able to load `https://localhost`:

```
const privateKey = fs.readFileSync('./certs/localhost-key.pem', 'utf8');
const certificate = fs.readFileSync('./certs/localhost.pem', 'utf8');
const credentials = { key: privateKey, cert: certificate };
const app = express();
const httpsServer = https.createServer(credentials, app);
```

However, I have a separate python script that I want to be able to access my local server.

This works fine and I'm able to see the proper JSON response:

```
def getUrlsToScrape():
  r = requests.get('https://localhost:1979/companies/urls', verify=False)
  return r.json()
```

However, I'd like to remove my warning so I tried referencing my cert and key files like below:

```
def getUrlsToScrape():
  r = requests.get('https://localhost:1979/companies/urls', cert=(os.path.join(dirname, '../../certs/localhost.pem'), os.path.join(dirname, '../../certs/localhost-key.pem')))
  return r.json()
```

but unfortunately I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 441, in wrap_socket
    cnx.do_handshake()
  File "/usr/local/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1907, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1639, in _raise_ssl_error
    _raise_current_error()
  File "/usr/local/lib/python3.6/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 448, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=1979): Max retries exceeded with url: /companies/urls (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify
failed')],)",),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/scripts/li_scrape.py", line 56, in <module>
    urlsToScrape = getUrlsToScrape()
  File "src/scripts/li_scrape.py", line 28, in getUrlsToScrape
    os.path.join(dirname, '../../certs/localhost-key.pem')))
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='localhost', port=1979): Max retries exceeded with url: /companies/urls (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
```

I am using the requests library, using instructions here - http://docs.python-requests.org/en/master/user/advanced/?highlight=ssl#client-side-certificates

**Comment by FiloSottile** [comment]
The verify argument is meant for the CA roots, not for the certificate itself (or its key, as usually the client doesn't have prior access to those).

What happens if you just run `requests.get('https://localhost:1979/companies/urls')` for the default behavior?

**Comment by FiloSottile** [comment]
Client certificates are not what you want to use here, `verify` is the right argument.

I am not sure what root store *requests* uses, but apparently not the system one. I can't look deeper into it now, but it should probably work if you set `verify` to `$CAROOT/rootCA.pem` where `$CAROOT` is the value returned by `mkcert -CAROOT`.

**Comment by shomanishikawa** [comment]
that worked! thank you!

Closing the question. Here is the working code:

```
def getUrlsToScrape():
  r = requests.get('https://localhost:1979/companies/urls', verify='/Users/shoma/Library/Application Support/mkcert/rootCA.pem')
  return r.json()
```

**Comment by adamdecaf** [comment]
I think that library uses https://github.com/certifi/python-certifi, which embeds the roots in code.

**Comment by dingobar** [comment]
> You can add the mkcert root ca to certifi's Root Certificates using:
> 
> ```
> cat "`mkcert -CAROOT`/rootCA.pem" >> `python -m certifi`
> ```
> 
> Which will make requests happy in that env.

Hi, is this the recommended way to get around the python `certifi` issue? I realize this is not really a `mkcert` problem but it would be nice to know if the community here has an opinion on it.

**Comment by gkreitz** [comment]
One can also use an environment variable to change what `requests` uses:
```
export REQUESTS_CA_BUNDLE=`mkcert -CAROOT`/rootCA.pem
```
